import { Links } from "@/modules/auth/pages/core/types/link.type";

export const languageList: Links[] = [
  { href: "#", label: "English (UK)" },
  { href: "#", label: "Tiếng Việt" },
  { href: "#", label: "中文(台灣)" },
  { href: "#", label: "한국어" },
  { href: "#", label: "日本語" },
  { href: "#", label: "Français (France)" },
  { href: "#", label: "ภาษาไทย" },
  { href: "#", label: "Español" },
  { href: "#", label: "Português (Brasil)" },
  { href: "#", label: "Deutsch" },
  { href: "#", label: "Italiano" },
  { href: "#", label: "+" },
];

export const menuList: Links[] = [
  { href: "#", label: "Sign Up" },
  { href: "#", label: "Log in" },
  { href: "#", label: "Messenger" },
  { href: "#", label: "Facebook Lite" },
  { href: "#", label: "Video" },
  { href: "#", label: "Places" },
  { href: "#", label: "Games" },
  { href: "#", label: "Marketplace" },
  { href: "#", label: "Meta Pay" },
  { href: "#", label: "Meta Store" },
  { href: "#", label: "Meta Quest" },
  { href: "#", label: "Meta Portal" },
  { href: "#", label: "Meta AI" },
  { href: "#", label: "Instagram" },
  { href: "#", label: "Threads" },
  { href: "#", label: "Fundraisers" },
  { href: "#", label: "Services" },
  { href: "#", label: "Voting Information Centre" },
  { href: "#", label: "Privacy Policy" },
  { href: "#", label: "Privacy Centre" },
  { href: "#", label: "Groups" },
  { href: "#", label: "About" },
  { href: "#", label: "Create ad" },
  { href: "#", label: "Create Page" },
  { href: "#", label: "Developers" },
  { href: "#", label: "Careers" },
  { href: "#", label: "Cookies" },
  { href: "#", label: "AdChoices" },
  { href: "#", label: "Terms" },
  { href: "#", label: "Help" },
  { href: "#", label: "Contact" },
  { href: "#", label: "Terms" },
  { href: "#", label: "Contact uploading and non-users" },
];
